"""Add involved_staff to events

Revision ID: d780087b4b53
Revises: fdccad5d0e8b
Create Date: 2026-03-27 08:01:45.313575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd780087b4b53'
down_revision: Union[str, None] = 'fdccad5d0e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('involved_staff', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'involved_staff')
    # ### end Alembic commands ###
