"""Initial schema

Revision ID: fdccad5d0e8b
Revises: 
Create Date: 2026-03-26 14:14:13.798527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdccad5d0e8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('MHRA_DRUG', 'MHRA_DEVICE', 'DRUG_SAFETY_UPDATE', 'NATPSA', 'CAS', name='alertsource'), nullable=False),
    sa.Column('content_id', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETE', 'NOT_APPLICABLE', name='alertstatus'), nullable=False),
    sa.Column('priority', sa.Enum('P1_URGENT', 'P2_IMPORTANT', 'P3_ROUTINE', name='alertpriority'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('event_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ui_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_policy_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cqc_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('evidence_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cqc_key_question', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'EXPORTED', 'FAILED', name='evidencepackstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.Enum('PATIENT_ACCESS', 'CLINICAL_SAFETY', 'CLINICAL_QUALITY', 'INFORMATION_GOVERNANCE', 'PATIENT_EXPERIENCE', 'IPC_HEALTH_SAFETY', 'WORKFORCE', 'BUSINESS_RESILIENCE', 'GOVERNANCE', name='policydomain'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'UNDER_REVIEW', 'SUPERSEDED', 'ARCHIVED', name='policystatus'), nullable=False),
    sa.Column('policy_lead_email', sa.String(length=255), nullable=True),
    sa.Column('policy_lead_name', sa.String(length=255), nullable=True),
    sa.Column('review_frequency_months', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('next_review_due', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('key_workflows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_checkpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('docx_path', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('CLINICAL_SAFETY', 'STAFFING', 'INFORMATION_GOVERNANCE', 'PREMISES', 'BUSINESS_CONTINUITY', 'PATIENT_SAFETY', 'FINANCIAL', 'REGULATORY', 'OPERATIONAL', 'REPUTATIONAL', name='riskcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MITIGATED', 'CLOSED', 'ESCALATED', name='riskstatus'), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('existing_controls', sa.Text(), nullable=True),
    sa.Column('gaps_in_control', sa.Text(), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('date_identified', sa.Date(), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('next_review_due', sa.Date(), nullable=True),
    sa.Column('linked_policy_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closure_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_clinical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alert_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by_email', sa.String(length=255), nullable=False),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('patients_identified', sa.Integer(), nullable=True),
    sa.Column('applies_to_practice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('external_message_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('MANDATORY_COMPLIANCE', 'TRAINING', 'IT_ACCESS', 'ONBOARDING', 'HR', 'CLINICAL', 'EQUIPMENT', 'PREMISES', name='checkcategory'), nullable=False),
    sa.Column('frequency_months', sa.Integer(), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('document_description', sa.String(length=500), nullable=True),
    sa.Column('applicable_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_job_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cqc_relevant', sa.Boolean(), nullable=False),
    sa.Column('cqc_quality_statement', sa.String(length=200), nullable=True),
    sa.Column('linked_policy_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['linked_policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'SEVERE', 'CATASTROPHIC', name='eventseverity'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_INVESTIGATION', 'DISCUSSED', 'ACTIONS_ASSIGNED', 'CLOSED', name='eventstatus'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reported_by_email', sa.String(length=255), nullable=False),
    sa.Column('reported_by_name', sa.String(length=255), nullable=False),
    sa.Column('investigator_email', sa.String(length=255), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('learning_outcomes', sa.Text(), nullable=True),
    sa.Column('discussed_at_meeting', sa.Boolean(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('duty_of_candour_required', sa.Boolean(), nullable=False),
    sa.Column('duty_of_candour_completed', sa.Boolean(), nullable=False),
    sa.Column('linked_policy_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_risk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cqc_quality_statement', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['evidence_packs.id'], name='fk_evidence_items_pack_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_acknowledgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('version_acknowledged', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_cqc_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('key_question', sa.Enum('SAFE', 'EFFECTIVE', 'CARING', 'RESPONSIVE', 'WELL_LED', name='cqckeyquestion'), nullable=False),
    sa.Column('quality_statement', sa.String(length=200), nullable=False),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('docx_path', sa.String(length=500), nullable=True),
    sa.Column('content_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_email', sa.String(length=255), nullable=False),
    sa.Column('reviewed_by_name', sa.String(length=255), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('likelihood_after', sa.Integer(), nullable=True),
    sa.Column('impact_after', sa.Integer(), nullable=True),
    sa.Column('score_after', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meeting_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('event_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_template_id', sa.UUID(), nullable=False),
    sa.Column('staff_email', sa.String(length=255), nullable=False),
    sa.Column('staff_name', sa.String(length=255), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_template_id'], ['check_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_check_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['staff_check_id'], ['staff_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_documents')
    op.drop_table('staff_checks')
    op.drop_table('event_history')
    op.drop_table('event_actions')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('risk_reviews')
    op.drop_table('risk_actions')
    op.drop_table('policy_versions')
    op.drop_table('policy_cqc_mappings')
    op.drop_table('policy_acknowledgments')
    op.drop_table('evidence_items')
    op.drop_table('events')
    op.drop_table('check_templates')
    op.drop_table('alert_notifications')
    op.drop_table('alert_actions')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('risks')
    op.drop_table('policies')
    op.drop_table('permissions')
    op.drop_table('evidence_packs')
    op.drop_table('event_types')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('alerts')
    # ### end Alembic commands ###
